package entite;
// Generated Apr 8, 2018 2:33:08 AM by Tp2Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private BigDecimal idcategorie;
     private String nom;
     private String description;
     private Set medicaments = new HashSet(0);

    public Categories() {
    }

	
    public Categories(BigDecimal idcategorie, String nom) {
        this.idcategorie = idcategorie;
        this.nom = nom;
    }
    public Categories(BigDecimal idcategorie, String nom, String description, Set medicaments) {
       this.idcategorie = idcategorie;
       this.nom = nom;
       this.description = description;
       this.medicaments = medicaments;
    }
   
    public BigDecimal getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(BigDecimal idcategorie) {
        this.idcategorie = idcategorie;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMedicaments() {
        return this.medicaments;
    }
    
    public void setMedicaments(Set medicaments) {
        this.medicaments = medicaments;
    }




}


