package entite;
// Generated Apr 8, 2018 2:33:08 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chirurgie generated by hbm2java
 */
public class Chirurgie  implements java.io.Serializable {


     private BigDecimal idchir;
     private Salle salle;
     private Typechirurgie typechirurgie;
     private Date datechirurgie;
     private BigDecimal heuredebut;
     private BigDecimal heurefin;
     private Set ordonnancechirurgies = new HashSet(0);

    public Chirurgie() {
    }

	
    public Chirurgie(BigDecimal idchir) {
        this.idchir = idchir;
    }
    public Chirurgie(BigDecimal idchir, Salle salle, Typechirurgie typechirurgie, Date datechirurgie, BigDecimal heuredebut, BigDecimal heurefin, Set ordonnancechirurgies) {
       this.idchir = idchir;
       this.salle = salle;
       this.typechirurgie = typechirurgie;
       this.datechirurgie = datechirurgie;
       this.heuredebut = heuredebut;
       this.heurefin = heurefin;
       this.ordonnancechirurgies = ordonnancechirurgies;
    }
   
    public BigDecimal getIdchir() {
        return this.idchir;
    }
    
    public void setIdchir(BigDecimal idchir) {
        this.idchir = idchir;
    }
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }
    public Typechirurgie getTypechirurgie() {
        return this.typechirurgie;
    }
    
    public void setTypechirurgie(Typechirurgie typechirurgie) {
        this.typechirurgie = typechirurgie;
    }
    public Date getDatechirurgie() {
        return this.datechirurgie;
    }
    
    public void setDatechirurgie(Date datechirurgie) {
        this.datechirurgie = datechirurgie;
    }
    public BigDecimal getHeuredebut() {
        return this.heuredebut;
    }
    
    public void setHeuredebut(BigDecimal heuredebut) {
        this.heuredebut = heuredebut;
    }
    public BigDecimal getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(BigDecimal heurefin) {
        this.heurefin = heurefin;
    }
    public Set getOrdonnancechirurgies() {
        return this.ordonnancechirurgies;
    }
    
    public void setOrdonnancechirurgies(Set ordonnancechirurgies) {
        this.ordonnancechirurgies = ordonnancechirurgies;
    }




}


