package entite;
// Generated Apr 8, 2018 2:33:08 AM by Tp2Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dossierpatient generated by hbm2java
 */
public class Dossierpatient  implements java.io.Serializable {


     private BigDecimal numdos;
     private Docteur docteur;
     private String nomp;
     private String prenomp;
     private String sexe;
     private BigDecimal numas;
     private Date datenaiss;
     private Date datec;
     private BigDecimal nbrconsultation;
     private Set consultations = new HashSet(0);

    public Dossierpatient() {
    }

	
    public Dossierpatient(BigDecimal numdos, String nomp, String prenomp) {
        this.numdos = numdos;
        this.nomp = nomp;
        this.prenomp = prenomp;
    }
    public Dossierpatient(BigDecimal numdos, Docteur docteur, String nomp, String prenomp, String sexe, BigDecimal numas, Date datenaiss, Date datec, BigDecimal nbrconsultation, Set consultations) {
       this.numdos = numdos;
       this.docteur = docteur;
       this.nomp = nomp;
       this.prenomp = prenomp;
       this.sexe = sexe;
       this.numas = numas;
       this.datenaiss = datenaiss;
       this.datec = datec;
       this.nbrconsultation = nbrconsultation;
       this.consultations = consultations;
    }
   
    public BigDecimal getNumdos() {
        return this.numdos;
    }
    
    public void setNumdos(BigDecimal numdos) {
        this.numdos = numdos;
    }
    public Docteur getDocteur() {
        return this.docteur;
    }
    
    public void setDocteur(Docteur docteur) {
        this.docteur = docteur;
    }
    public String getNomp() {
        return this.nomp;
    }
    
    public void setNomp(String nomp) {
        this.nomp = nomp;
    }
    public String getPrenomp() {
        return this.prenomp;
    }
    
    public void setPrenomp(String prenomp) {
        this.prenomp = prenomp;
    }
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }
    public BigDecimal getNumas() {
        return this.numas;
    }
    
    public void setNumas(BigDecimal numas) {
        this.numas = numas;
    }
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }
    public BigDecimal getNbrconsultation() {
        return this.nbrconsultation;
    }
    
    public void setNbrconsultation(BigDecimal nbrconsultation) {
        this.nbrconsultation = nbrconsultation;
    }
    public Set getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }




}


