package entite;
// Generated Apr 8, 2018 2:33:08 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Specialisationsalle generated by hbm2java
 */
public class Specialisationsalle  implements java.io.Serializable {


     private SpecialisationsalleId id;
     private Salle salle;
     private Typechirurgie typechirurgie;
     private Date datec;

    public Specialisationsalle() {
    }

	
    public Specialisationsalle(SpecialisationsalleId id, Salle salle, Typechirurgie typechirurgie) {
        this.id = id;
        this.salle = salle;
        this.typechirurgie = typechirurgie;
    }
    public Specialisationsalle(SpecialisationsalleId id, Salle salle, Typechirurgie typechirurgie, Date datec) {
       this.id = id;
       this.salle = salle;
       this.typechirurgie = typechirurgie;
       this.datec = datec;
    }
   
    public SpecialisationsalleId getId() {
        return this.id;
    }
    
    public void setId(SpecialisationsalleId id) {
        this.id = id;
    }
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }
    public Typechirurgie getTypechirurgie() {
        return this.typechirurgie;
    }
    
    public void setTypechirurgie(Typechirurgie typechirurgie) {
        this.typechirurgie = typechirurgie;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }




}


