package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by Tp2Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordonnance generated by hbm2java
 */
public class Ordonnance  implements java.io.Serializable {


     private BigDecimal numord;
     private String recommandations;
     private String type;
     private Date datec;
     private BigDecimal nbrmedicaments;
     private Set ordonnancemedicamentses = new HashSet(0);
     private Set consultations = new HashSet(0);
     private Set ordonnancechirurgies = new HashSet(0);

    public Ordonnance() {
    }

	
    public Ordonnance(BigDecimal numord) {
        this.numord = numord;
    }
    public Ordonnance(BigDecimal numord, String recommandations, String type, Date datec, BigDecimal nbrmedicaments, Set ordonnancemedicamentses, Set consultations, Set ordonnancechirurgies) {
       this.numord = numord;
       this.recommandations = recommandations;
       this.type = type;
       this.datec = datec;
       this.nbrmedicaments = nbrmedicaments;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
       this.consultations = consultations;
       this.ordonnancechirurgies = ordonnancechirurgies;
    }
   
    public BigDecimal getNumord() {
        return this.numord;
    }
    
    public void setNumord(BigDecimal numord) {
        this.numord = numord;
    }
    public String getRecommandations() {
        return this.recommandations;
    }
    
    public void setRecommandations(String recommandations) {
        this.recommandations = recommandations;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }
    public BigDecimal getNbrmedicaments() {
        return this.nbrmedicaments;
    }
    
    public void setNbrmedicaments(BigDecimal nbrmedicaments) {
        this.nbrmedicaments = nbrmedicaments;
    }
    public Set getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }
    
    public void setOrdonnancemedicamentses(Set ordonnancemedicamentses) {
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }
    public Set getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }
    public Set getOrdonnancechirurgies() {
        return this.ordonnancechirurgies;
    }
    
    public void setOrdonnancechirurgies(Set ordonnancechirurgies) {
        this.ordonnancechirurgies = ordonnancechirurgies;
    }

    @Override
    public String toString() {
        return "Ordonnance{" +
                "numord=" + numord +
                ", recommandations='" + recommandations + '\'' +
                ", type='" + type + '\'' +
                ", datec=" + datec +
                ", nbrmedicaments=" + nbrmedicaments +
                '}';
    }
}


