package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OrdonnancechirurgieId generated by hbm2java
 */
public class OrdonnancechirurgieId  implements java.io.Serializable {


     private BigDecimal numord;
     private BigDecimal idchir;

    public OrdonnancechirurgieId() {
    }

    public OrdonnancechirurgieId(BigDecimal numord, BigDecimal idchir) {
       this.numord = numord;
       this.idchir = idchir;
    }
   
    public BigDecimal getNumord() {
        return this.numord;
    }
    
    public void setNumord(BigDecimal numord) {
        this.numord = numord;
    }
    public BigDecimal getIdchir() {
        return this.idchir;
    }
    
    public void setIdchir(BigDecimal idchir) {
        this.idchir = idchir;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancechirurgieId) ) return false;
		 OrdonnancechirurgieId castOther = ( OrdonnancechirurgieId ) other; 
         
		 return ( (this.getNumord()==castOther.getNumord()) || ( this.getNumord()!=null && castOther.getNumord()!=null && this.getNumord().equals(castOther.getNumord()) ) )
 && ( (this.getIdchir()==castOther.getIdchir()) || ( this.getIdchir()!=null && castOther.getIdchir()!=null && this.getIdchir().equals(castOther.getIdchir()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumord() == null ? 0 : this.getNumord().hashCode() );
         result = 37 * result + ( getIdchir() == null ? 0 : this.getIdchir().hashCode() );
         return result;
   }

    @Override
    public String toString() {
        return "OrdonnancechirurgieId{" +
                "numord=" + numord +
                ", idchir=" + idchir +
                '}';
    }
}


