package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by HibernateUtil Tools 4.3.1


import java.math.BigDecimal;

/**
 * Ordonnancemedicaments generated by hbm2java
 */
public class Ordonnancemedicaments  implements java.io.Serializable {


     private OrdonnancemedicamentsId id;
     private Ordonnance ordonnance;
     private Medicament medicament;
     private BigDecimal nbboites;

    public Ordonnancemedicaments() {
    }

	
    public Ordonnancemedicaments(OrdonnancemedicamentsId id, Ordonnance ordonnance, Medicament medicament) {
        this.id = id;
        this.ordonnance = ordonnance;
        this.medicament = medicament;
    }
    public Ordonnancemedicaments(OrdonnancemedicamentsId id, Ordonnance ordonnance, Medicament medicament, BigDecimal nbboites) {
       this.id = id;
       this.ordonnance = ordonnance;
       this.medicament = medicament;
       this.nbboites = nbboites;
    }
   
    public OrdonnancemedicamentsId getId() {
        return this.id;
    }
    
    public void setId(OrdonnancemedicamentsId id) {
        this.id = id;
    }
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }
    public Medicament getMedicament() {
        return this.medicament;
    }
    
    public void setMedicament(Medicament medicament) {
        this.medicament = medicament;
    }
    public BigDecimal getNbboites() {
        return this.nbboites;
    }
    
    public void setNbboites(BigDecimal nbboites) {
        this.nbboites = nbboites;
    }

    @Override
    public String toString() {
        return "Ordonnancemedicaments{" +
                "id=" + id +
                ", ordonnance=" + ordonnance +
                ", medicament=" + medicament +
                ", nbboites=" + nbboites +
                '}';
    }
}


