package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by Tp2Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Salle generated by hbm2java
 */
public class Salle  implements java.io.Serializable {


     private BigDecimal idsalle;
     private String nom;
     private Set specialisationsalles = new HashSet(0);
     private Set chirurgies = new HashSet(0);

    public Salle() {
    }

	
    public Salle(BigDecimal idsalle, String nom) {
        this.idsalle = idsalle;
        this.nom = nom;
    }
    public Salle(BigDecimal idsalle, String nom, Set specialisationsalles, Set chirurgies) {
       this.idsalle = idsalle;
       this.nom = nom;
       this.specialisationsalles = specialisationsalles;
       this.chirurgies = chirurgies;
    }
   
    public BigDecimal getIdsalle() {
        return this.idsalle;
    }
    
    public void setIdsalle(BigDecimal idsalle) {
        this.idsalle = idsalle;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getSpecialisationsalles() {
        return this.specialisationsalles;
    }
    
    public void setSpecialisationsalles(Set specialisationsalles) {
        this.specialisationsalles = specialisationsalles;
    }
    public Set getChirurgies() {
        return this.chirurgies;
    }
    
    public void setChirurgies(Set chirurgies) {
        this.chirurgies = chirurgies;
    }

    @Override
    public String toString() {
        return "Salle{" +
                "idsalle=" + idsalle +
                ", nom='" + nom + '\'' +
                '}';
    }
}


