package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by Tp2Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SpecialisationsalleId generated by hbm2java
 */
public class SpecialisationsalleId  implements java.io.Serializable {


     private BigDecimal idtype;
     private BigDecimal idsalle;

    public SpecialisationsalleId() {
    }

    public SpecialisationsalleId(BigDecimal idtype, BigDecimal idsalle) {
       this.idtype = idtype;
       this.idsalle = idsalle;
    }
   
    public BigDecimal getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(BigDecimal idtype) {
        this.idtype = idtype;
    }
    public BigDecimal getIdsalle() {
        return this.idsalle;
    }
    
    public void setIdsalle(BigDecimal idsalle) {
        this.idsalle = idsalle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpecialisationsalleId) ) return false;
		 SpecialisationsalleId castOther = ( SpecialisationsalleId ) other; 
         
		 return ( (this.getIdtype()==castOther.getIdtype()) || ( this.getIdtype()!=null && castOther.getIdtype()!=null && this.getIdtype().equals(castOther.getIdtype()) ) )
 && ( (this.getIdsalle()==castOther.getIdsalle()) || ( this.getIdsalle()!=null && castOther.getIdsalle()!=null && this.getIdsalle().equals(castOther.getIdsalle()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdtype() == null ? 0 : this.getIdtype().hashCode() );
         result = 37 * result + ( getIdsalle() == null ? 0 : this.getIdsalle().hashCode() );
         return result;
   }

    @Override
    public String toString() {
        return "SpecialisationsalleId{" +
                "idtype=" + idtype +
                ", idsalle=" + idsalle +
                '}';
    }
}


