package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by tp2Hibernate.Tp2Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Specialite generated by hbm2java
 */
public class Specialite  implements java.io.Serializable {


     private BigDecimal code;
     private String titre;
     private String description;
     private Set docteurs = new HashSet(0);

    public Specialite() {
    }

	
    public Specialite(BigDecimal code, String titre) {
        this.code = code;
        this.titre = titre;
    }
    public Specialite(BigDecimal code, String titre, String description, Set docteurs) {
       this.code = code;
       this.titre = titre;
       this.description = description;
       this.docteurs = docteurs;
    }
   
    public BigDecimal getCode() {
        return this.code;
    }
    
    public void setCode(BigDecimal code) {
        this.code = code;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getDocteurs() {
        return this.docteurs;
    }
    
    public void setDocteurs(Set docteurs) {
        this.docteurs = docteurs;
    }


    @Override
    public String toString() {
        return "Specialite{" +
                "code=" + code +
                ", titre='" + titre + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}


