package tp2Hibernate.entite;
// Generated Apr 8, 2018 2:33:08 AM by tp2Hibernate.HibernateUtil Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Typechirurgie generated by hbm2java
 */
public class Typechirurgie  implements java.io.Serializable {


     private BigDecimal idtype;
     private String nom;
     private String description;
     private Set chirurgies = new HashSet(0);
     private Set specialisationsalles = new HashSet(0);

    public Typechirurgie() {
    }

	
    public Typechirurgie(BigDecimal idtype, String nom) {
        this.idtype = idtype;
        this.nom = nom;
    }
    public Typechirurgie(BigDecimal idtype, String nom, String description, Set chirurgies, Set specialisationsalles) {
       this.idtype = idtype;
       this.nom = nom;
       this.description = description;
       this.chirurgies = chirurgies;
       this.specialisationsalles = specialisationsalles;
    }
   
    public BigDecimal getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(BigDecimal idtype) {
        this.idtype = idtype;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getChirurgies() {
        return this.chirurgies;
    }
    
    public void setChirurgies(Set chirurgies) {
        this.chirurgies = chirurgies;
    }
    public Set getSpecialisationsalles() {
        return this.specialisationsalles;
    }
    
    public void setSpecialisationsalles(Set specialisationsalles) {
        this.specialisationsalles = specialisationsalles;
    }


    @Override
    public String toString() {
        return "Typechirurgie{" +
                "idtype=" + idtype +
                ", nom='" + nom + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}


